### ISSUE TITLE
Model Registry not available

### ISSUE THREAD

**Issue by angel539** [Snowflake-Labs/sfguide-intro-to-machine-learning-with-snowpark-ml-for-python#11]
Hi,

I have tried this tutorial with a free Snowflake account (Enterprise) in Ireland, Netherlands and London for Azure. In the notebook https://github.com/Snowflake-Labs/sfquickstarts/pull/3, Model Registry has been tested, but this feature is still not available for all the accounts as it is referred to in the Snowflake documentation:

https://docs.snowflake.com/LIMITEDACCESS/snowflake-ml-model-registry?_fsi=QE1ZnTCS

(PREVIEW FEATURE — PRIVATE
Support for this feature is currently not in production and is only available to selected accounts.)

Is there a workaround I could try?

Cheers,

Ángel

**Comment by sfc-gh-xjiang** [comment]
Hi Ángel,

Nice to meet you. Model registry is now in public preview, please refer to the [documentation](https://docs.snowflake.com/en/developer-guide/snowpark-ml/snowpark-ml-mlops-model-registry) and feel free to try it out!

Thanks
Xinyi

**Comment by sfc-gh-sdas** [comment]
Can we close this issue now?
