### ISSUE TITLE
Apple silicon workaround vis-a-vis this tutorial

### ISSUE THREAD

**Issue by uwo** [Snowflake-Labs/sfguide-intro-to-machine-learning-with-snowpark-ml-for-python#14]
Hello! I'm just getting started with Snowpark and I'd like to do the quickstart guide associated with this tutorial.  In the workaround mentioned [here](https://docs.snowflake.com/en/developer-guide/snowpark/python/setup#prerequisites), it mentions using python=3.8 like so:

`CONDA_SUBDIR=osx-64 conda create -n snowpark python=3.8 numpy pandas pyarrow --override-channels -c https://repo.anaconda.com/pkgs/snowflake`

I see that this project currently uses 3.10. Should I downgrade python to 3.8 in `conda_env.yml`?

**Comment by sfc-gh-sidas** [comment]
You can still use python=3.10 in this project, and it should still work.
